# Generated by Django 4.1.3 on 2023-11-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_description_task_club2_task_golesclub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='club2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='golesclub',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='golesclub2',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
