# Generated by Django 4.1.3 on 2023-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_club2_alter_task_golesclub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='golesclub',
            field=models.TextField(default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='golesclub2',
            field=models.TextField(default=False, max_length=200, null=True),
        ),
    ]
