# Generated by Django 4.1.3 on 2023-11-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_golesclub_alter_task_golesclub2'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='golesclub',
            field=models.TextField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='golesclub2',
            field=models.TextField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
